### PR TITLE
use wget instead of curl & clear dalvik-cache upon installation

### PR DESCRIPTION
**Pull request by rahilarious**
why download extra 3 mb? yeah wget is bit insecure but so is rooting xD
also clear dalvik-cache while installing so when you update module with updated apk dex dont conflict. 
If they conflict they'll give black screen after booting.

### CODE REVIEW

**Comment by skittles9823** [comment]
Would probs be best to prepend $PATH with /sbin/.magisk/busybox for this. Have you tested it using magisks busybox? I'm not quite sure if the networking issues have been fixed.

**Comment by rahilarious** [comment]
> Would probs be best to prepend $PATH with /sbin/.magisk/busybox for this. Have you tested it using magisks busybox? I'm not quite sure if the networking issues have been fixed.

I tested this with only magisk (no modules) installed. It works. Merge and test it out yourself

**Comment by skittles9823** [comment]
> I tested this with only magisk (no modules) installed. It works. Merge and test it out yourself

Good to hear. I can't test it myself as I'm using a custom rom which has the active edge customisation built in so it would cause issues but if it works for you then sweet.

**Comment by jtothe4n** [comment]
@plethorahil ... I reverted the change, because a user just wrote in our telegram, that the module can't be installed. 
The remote Md5 is empty:
image

..After the revert, everything worked again:
image


Didn't want to debug it, because I don't have time for that now.

**Pull request merged**
